version: '3'
services:
  db:
    image: postgres:14.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  app:
    build: .
    environment:
      - DB_HOST=db
    ports: 
      - '${PORT}:${PORT}'
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    depends_on:
      - db
volumes:
  db-data: